AI2_projekt/Controllers/AdresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AI2_project.Models;

namespace AI2_project.Controllers
{
    public class AdresController : Controller
    {
        private BibliotekaEntities2 db = new BibliotekaEntities2();

        // GET: Adres
        public ActionResult Index()
        {
            return View(db.Adres.ToList());
        }

        // GET: Adres/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Adres adres = db.Adres.Find(id);
            if (adres == null)
            {
                return HttpNotFound();
            }
            return View(adres);
        }

        // GET: Adres/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Adres/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Miejscowość,Kod_pocztowy,Ulica,Nr_domu,Nr_lokalu")] Adres adres)
        {
            if (ModelState.IsValid)
            {
                db.Adres.Add(adres);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(adres);
        }

        // GET: Adres/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Adres adres = db.Adres.Find(id);
            if (adres == null)
            {
                return HttpNotFound();
            }
            return View(adres);
        }

        // POST: Adres/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Miejscowość,Kod_pocztowy,Ulica,Nr_domu,Nr_lokalu")] Adres adres)
        {
            if (ModelState.IsValid)
            {
                db.Entry(adres).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(adres);
        }

        // GET: Adres/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Adres adres = db.Adres.Find(id);
            if (adres == null)
            {
                return HttpNotFound();
            }
            return View(adres);
        }

        // POST: Adres/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Adres adres = db.Adres.Find(id);
            db.Adres.Remove(adres);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AI2_projekt/Controllers/KsiazkiController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AI2_project.Models;

namespace AI2_project.Controllers
{
    public class KsiazkiController : Controller
    {
        private BibliotekaEntities2 db = new BibliotekaEntities2();

        // GET: Ksiazki
        public ActionResult Index()
        {
            var ksiazki = db.Ksiazki.Include(k => k.Kategorie);
            return View(ksiazki.ToList());
        }

        // GET: Ksiazki/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ksiazki ksiazki = db.Ksiazki.Find(id);
            if (ksiazki == null)
            {
                return HttpNotFound();
            }
            return View(ksiazki);
        }

        public ActionResult Wypozycz(bool confirm,int? id)
        {
            if (confirm == true)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Ksiazki ksiazki = db.Ksiazki.Find(id);
                if (ksiazki == null)
                {
                    return HttpNotFound();
                }
                ksiazki.Ilość_na_stanie--;
                Wypozyczenia wyp = new Wypozyczenia();
                wyp.Wypożyczający = int.Parse(Session["userId"].ToString());
                wyp.Książka = int.Parse(ksiazki.Id.ToString());
                wyp.Status = 1;
                wyp.Data_rezerwacji = DateTime.Today;
                db.Wypozyczenia.Add(wyp);
                db.SaveChanges();
            }
            else { }
            return View();
            
        }

        // GET: Ksiazki/Create
        //public ActionResult Create()
        //{
        //    ViewBag.Kategoria = new SelectList(db.Kategorie, "Id", "Kategoria");
        //    return View();
        //}

        //// POST: Ksiazki/Create
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "Id,Tytuł,Kategoria,Autor,Opis,Rok_wydania,Ilość_na_stanie")] Ksiazki ksiazki)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Ksiazki.Add(ksiazki);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    ViewBag.Kategoria = new SelectList(db.Kategorie, "Id", "Kategoria", ksiazki.Kategoria);
        //    return View(ksiazki);
        //}

        //// GET: Ksiazki/Edit/5
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Ksiazki ksiazki = db.Ksiazki.Find(id);
        //    if (ksiazki == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    ViewBag.Kategoria = new SelectList(db.Kategorie, "Id", "Kategoria", ksiazki.Kategoria);
        //    return View(ksiazki);
        //}

        //// POST: Ksiazki/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "Id,Tytuł,Kategoria,Autor,Opis,Rok_wydania,Ilość_na_stanie")] Ksiazki ksiazki)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(ksiazki).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    ViewBag.Kategoria = new SelectList(db.Kategorie, "Id", "Kategoria", ksiazki.Kategoria);
        //    return View(ksiazki);
        //}

        //// GET: Ksiazki/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Ksiazki ksiazki = db.Ksiazki.Find(id);
        //    if (ksiazki == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(ksiazki);
        //}

        //// POST: Ksiazki/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    Ksiazki ksiazki = db.Ksiazki.Find(id);
        //    db.Ksiazki.Remove(ksiazki);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AI2_projekt/Controllers/OsobyController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AI2_project.Models;

namespace AI2_project.Controllers
{
    public class OsobyController : Controller
    {
        private BibliotekaEntities2 db = new BibliotekaEntities2();

        // GET: Osoby
        public ActionResult Index()
        {
            var osoba = db.Osoba.Include(o => o.Adres1);
            return View(osoba.ToList());
        }

        // GET: Osoby/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Osoba osoba = db.Osoba.Find(id);
            if (osoba == null)
            {
                return HttpNotFound();
            }
            return View(osoba);
        }

        // GET: Osoby/Create
        public ActionResult Create()
        {
            ViewBag.Adres = new SelectList(db.Adres, "Id", "Miejscowość");
            return View();
        }

        // POST: Osoby/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Adres,Imie,Nazwisko,telefon,email")] Osoba osoba)
        {
            if (ModelState.IsValid)
            {
                db.Osoba.Add(osoba);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Adres = new SelectList(db.Adres, "Id", "Miejscowość", osoba.Adres);
            return View(osoba);
        }

        // GET: Osoby/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Osoba osoba = db.Osoba.Find(id);
            if (osoba == null)
            {
                return HttpNotFound();
            }
            ViewBag.Adres = new SelectList(db.Adres, "Id", "Miejscowość", osoba.Adres);
            return View(osoba);
        }

        // POST: Osoby/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Adres,Imie,Nazwisko,telefon,email")] Osoba osoba)
        {
            if (ModelState.IsValid)
            {
                db.Entry(osoba).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Adres = new SelectList(db.Adres, "Id", "Miejscowość", osoba.Adres);
            return View(osoba);
        }

        // GET: Osoby/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Osoba osoba = db.Osoba.Find(id);
            if (osoba == null)
            {
                return HttpNotFound();
            }
            return View(osoba);
        }

        // POST: Osoby/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Osoba osoba = db.Osoba.Find(id);
            db.Osoba.Remove(osoba);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AI2_projekt/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                    @Html.ActionLink("Bilbioteka", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Lista Książek", "Index", "Ksiazki")</li>
                    @if (Session["userID"] != null)
                    {
                        <li>@Html.ActionLink("Wypozyczone", "Index", "Wypozyczone")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Zaloguj się", "Index", "Login")</li>
                    }
                    @if ((Session["userID"] != null) && (Session["roleID"].Equals(2)))
                    {
                        <li>@Html.ActionLink("Wypozyczanie", "Index", "Wypozycz")</li>
                        <li>@Html.ActionLink("Karty", "Index", "Karty")</li>
                        <li>@Html.ActionLink("Książki", "Index", "KsiazkiUser")</li>
                        <li>@Html.ActionLink("Klienci biblioteki", "Index", "Osoby")</li>
                        <li>@Html.ActionLink("Adresy", "Index", "Adres")</li>
                        <li>@Html.ActionLink("Kategorie", "Index", "Kategorie")</li>
                    }
                    @if ((Session["userID"] != null) && (Session["roleID"].Equals(3)))
                    {
                        <li>@Html.ActionLink("Wypozyczanie", "Index", "Wypozycz")</li>
                        <li>@Html.ActionLink("Karty", "Index", "Karty")</li>
                        <li>@Html.ActionLink("Książki", "Index", "KsiazkiUser")</li>
                        <li>@Html.ActionLink("Klienci biblioteki", "Index", "Osoby")</li>
                        <li>@Html.ActionLink("Adresy", "Index", "Adres")</li>
                        <li>@Html.ActionLink("Kategorie", "Index", "Kategorie")</li>
                        <li>@Html.ActionLink("Role", "Index", "Role")</li>
                    }
                    <li>@Html.ActionLink("O nas", "About", "Home")</li>
                    <li>@Html.ActionLink("Kontakt", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            @if (Session["userID"] != null) {
                <a href="@Url.Action("LogOut", "Login")">Wyloguj</a>
            }
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>